//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChartApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intervention
    {
        public int InterventionId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Activity1 { get; set; }
        public string Activity2 { get; set; }
        public string Activity3 { get; set; }
        public string Activity4 { get; set; }
        public System.DateTime DateTimeDone { get; set; }
        public string RouteGiven { get; set; }
        public string ResponeToTreatment { get; set; }
        public string HowTolerated { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
