//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChartApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int VisitId { get; set; }
        public int Room { get; set; }
        public System.DateTime VisitDate { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public Nullable<int> PatientId { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
